# Generated by Django 4.2.7 on 2024-01-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishcart', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
