# Generated by Django 4.2.7 on 2024-01-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishcart', '0003_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
    ]
