# Generated by Django 4.2.7 on 2023-11-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tshirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='discount',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
