# Generated by Django 4.2.7 on 2023-12-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_tshirt_image1_alter_tshirt_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tshirt',
        ),
    ]
