# Generated by Django 4.2.7 on 2023-12-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_remove_tshirt_category_delete_category_delete_tshirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MT', 'Men T-Shirts'), ('WT', 'Women T-Shirts'), ('KT', 'Kids T-Shirts'), ('CH', 'Characters')], default='MT', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='products/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('size', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('discount', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
