# Generated by Django 4.2.7 on 2023-12-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_tshirt_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='subcategory',
            field=models.CharField(choices=[('PN', 'Polo Neck'), ('VN', 'V-Neck'), ('HN', 'Henley Neck'), ('LS', 'Long Sleeves'), ('PT', 'Printed T-Shirts'), ('CT', 'Colorblock T-Shirts'), ('WN', 'Wide Neck Off Shoulder T-shirts'), ('YN', 'Yoke Neck T-shirts'), ('DB', 'Douche Bag Neck T-shirt')], default='PN', max_length=2),
        ),
    ]
