# Generated by Django 4.2.7 on 2023-12-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_tshirt_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='subcategory',
            field=models.CharField(choices=[('PN', 'Polo Neck'), ('HS', 'Half Sleeves'), ('HN', 'Henley Neck'), ('HD', 'Hoodies'), ('SL', 'Sleeveless'), ('SW', 'Sweatshirts'), ('LS', 'Long Sleeves'), ('PT', 'Printed T-Shirts'), ('CT', 'Colorblock T-Shirts')], default='PN', max_length=2),
        ),
    ]
