# Generated by Django 4.2.7 on 2023-12-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_tshirt_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='characters_subcategory',
            field=models.CharField(blank=True, choices=[('MR', 'Marvel'), ('DC', 'DC Comics'), ('MT', 'Movies & TV'), ('CA', 'Cartoons/Anime'), ('WS', 'Web Series')], max_length=2),
        ),
    ]
