# Generated by Django 4.2.7 on 2023-12-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_tshirt_characters_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='marvel_subcategory',
            field=models.CharField(blank=True, choices=[('AVM', 'Avengers'), ('SMM', 'Spider-Man'), ('IMM', 'Iron-Man'), ('CAM', 'Captain America'), ('TM', 'Thor'), ('LM', 'Loki'), ('DSM', 'Doctor Strange'), ('DPM', 'Dead Pool'), ('HM', 'Hulk'), ('BWM', 'Black Widow'), ('VM', 'Venom'), ('WVM', 'Wandavision'), ('AMM', 'Ant-Man'), ('CMM', 'Captain Marvel'), ('SCM', 'Shang Chi'), ('TM', 'Thanos'), ('BPM', 'Black Panther'), ('EM', 'Eternals')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='category',
            field=models.CharField(choices=[('MT', 'Men T-Shirts'), ('WT', 'Women T-Shirts'), ('KT', 'Kids T-Shirts')], default='MT', max_length=2),
        ),
    ]
