# Generated by Django 4.2.7 on 2023-12-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_tshirt_marvel_subcategory_alter_tshirt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='category',
            field=models.CharField(choices=[('MT', 'Men T-Shirts'), ('WT', 'Women T-Shirts'), ('KT', 'Kids T-Shirts'), ('CH', 'Characters')], default='MT', max_length=2),
        ),
    ]
