# Generated by Django 4.2.7 on 2023-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_tshirt_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tshirt',
            old_name='characters_subcategory',
            new_name='characters',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='cartoons_anime_subcategory',
            field=models.CharField(blank=True, choices=[('SC', 'Snoopy'), ('RMC', 'Rick and Morty'), ('LTC', 'Looney Tunes'), ('BBC', 'Bugs Bunny'), ('TC', 'Tweety'), ('SJC', 'Space Jam'), ('TJC', 'Tom and Jerry'), ('SDC', 'Scooby Doo'), ('DC', 'Disney'), ('MMC', 'Mickey Mouse'), ('DDC', 'Donald Duck'), ('SC', 'Samurai Jack Benlo'), ('BC', 'Ben 10'), ('SBC', 'Sponge Bob Square Pants'), ('FDC', 'Fidon Dido'), ('CBC', 'Chotta Beam'), ('MPC', 'Motu Patlu'), ('MC', 'Mowgli'), ('DMC', 'Doremon'), ('JAC', 'Jackiechan Adventure.'), ('LKC', 'Little krishna'), ('SC', 'Shiva'), ('DEC', 'Dora the Explorer')], max_length=3),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='dc_comics_subcategory',
            field=models.CharField(blank=True, choices=[('BBD', 'Blue Bleete'), ('JLD', 'Justice League'), ('BMD', 'Batman'), ('TFD', 'The Fish'), ('SMD', 'Super Man'), ('WWD', 'Wonder Woman'), ('SD', 'Shazam'), ('JD', 'Joker'), ('AMD', 'Aquaman'), ('GLD', 'Green Lantern'), ('HQD', 'Harley Quinn'), ('BAD', 'Black Adam'), ('SSD', 'Suide Sqaud')], max_length=3),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='movies_tv_subcategory',
            field=models.CharField(blank=True, choices=[('HPM', 'Harry Potter'), ('FM', 'Friends'), ('SWM', 'Star Wars'), ('TMM', 'The Mandalorian'), ('HDM', 'House of the Dragon'), ('GTM', 'Game of Thrones'), ('LKM', 'The Lion King')], max_length=3),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='web_series_subcategory',
            field=models.CharField(blank=True, choices=[('STW', 'Stranger Things'), ('WW', 'Wednesday'), ('NHW', 'Never Have I Ever'), ('EW', 'Elite'), ('PBW', 'Peaky Blinders'), ('LW', 'Lucifer'), ('ADW', 'All of us Are Dead'), ('SEW', 'Sex Education')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='category',
            field=models.CharField(choices=[('MT', 'Men T-Shirts'), ('WT', 'Women T-Shirts'), ('KT', 'Kids T-Shirts')], default='MT', max_length=2),
        ),
    ]
