# Generated by Django 4.2.7 on 2023-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_rename_characters_subcategory_tshirt_characters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='category',
            field=models.CharField(choices=[('MT', 'Men T-Shirts'), ('WT', 'Women T-Shirts'), ('KT', 'Kids T-Shirts'), ('CT', 'Characters')], default='MT', max_length=2),
        ),
    ]
