# Generated by Django 4.2.7 on 2023-12-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_tshirt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='cartoons_anime_subcategory',
            field=models.CharField(blank=True, choices=[('SNC', 'Snoopy'), ('RMC', 'Rick and Morty'), ('LTC', 'Looney Tunes'), ('BBC', 'Bugs Bunny'), ('TC', 'Tweety'), ('SJC', 'Space Jam'), ('TJC', 'Tom and Jerry'), ('SDC', 'Scooby Doo'), ('DC', 'Disney'), ('MMC', 'Mickey Mouse'), ('DDC', 'Donald Duck'), ('SJ', 'Samurai Jack'), ('BC', 'Ben 10'), ('SBC', 'Sponge Bob Square Pants'), ('FDC', 'Fidon Dido'), ('CBC', 'Chotta Beam'), ('MPC', 'Motu Patlu'), ('MC', 'Mowgli'), ('DMC', 'Doremon'), ('JAC', 'Jackiechan Adventure.'), ('LKC', 'Little krishna'), ('SC', 'Shiva'), ('DEC', 'Dora the Explorer')], max_length=3),
        ),
    ]
