# Generated by Django 4.2.7 on 2023-12-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_tshirt_cartoons_anime_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='characters',
            field=models.CharField(blank=True, choices=[('MR', 'Marvel'), ('DC', 'DC Comics'), ('MS', 'Movies & TV'), ('CA', 'Cartoons/Anime'), ('WS', 'Web Series')], max_length=2),
        ),
    ]
