# Generated by Django 4.2.7 on 2023-12-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0023_delete_tshirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('MT', 'Men T-Shirts'), ('WT', 'Women T-Shirts'), ('KT', 'Kids T-Shirts'), ('CT', 'Characters')], max_length=2)),
                ('subcategory', models.CharField(blank=True, choices=[('PN', 'Polo Neck'), ('HS', 'Half Sleeves'), ('HLN', 'Henley Neck'), ('HD', 'Hoodies'), ('SL', 'Sleeveless'), ('SW', 'Sweatshirts'), ('LS', 'Long Sleeves'), ('PT', 'Printed T-Shirts'), ('CBT', 'Colorblock T-Shirts'), ('VN', 'V-Neck'), ('WN', 'Wide Neck Off Shoulder T-shirts'), ('YN', 'Yoke Neck T-shirts'), ('DB', 'Douche Bag Neck T-shirt'), ('PLN', 'Plunge Neck'), ('CS', 'Cold Shoulder'), ('HN', 'High Neck'), ('CT', 'Collared T-shirts'), ('BW', 'Basic White T-Shirts'), ('BT', 'Boyfriend tees'), ('ST', 'Striped T-Shirts'), ('KC', 'Knot Crop'), ('SN', 'Scoop Neck'), ('CN', 'Crew Neck')], max_length=3)),
                ('characters', models.CharField(blank=True, choices=[('MR', 'Marvel'), ('DC', 'DC Comics'), ('MS', 'Movies & TV'), ('CA', 'Cartoons/Anime'), ('WS', 'Web Series')], max_length=2)),
                ('marvel_subcategory', models.CharField(blank=True, choices=[('AVM', 'Avengers'), ('SMM', 'Spider-Man'), ('IMM', 'Iron-Man'), ('CAM', 'Captain America'), ('TM', 'Thor'), ('LM', 'Loki'), ('DSM', 'Doctor Strange'), ('DPM', 'Dead Pool'), ('HM', 'Hulk'), ('BWM', 'Black Widow'), ('VM', 'Venom'), ('WVM', 'Wandavision'), ('AMM', 'Ant-Man'), ('CMM', 'Captain Marvel'), ('SCM', 'Shang Chi'), ('TM', 'Thanos'), ('BPM', 'Black Panther'), ('EM', 'Eternals')], max_length=3)),
                ('dc_comics_subcategory', models.CharField(blank=True, choices=[('BBD', 'Blue Bleete'), ('JLD', 'Justice League'), ('BMD', 'Batman'), ('TFD', 'The Fish'), ('SMD', 'Super Man'), ('WWD', 'Wonder Woman'), ('SD', 'Shazam'), ('JD', 'Joker'), ('AMD', 'Aquaman'), ('GLD', 'Green Lantern'), ('HQD', 'Harley Quinn'), ('BAD', 'Black Adam'), ('SSD', 'Suide Sqaud')], max_length=3)),
                ('movies_tv_subcategory', models.CharField(blank=True, choices=[('HPM', 'Harry Potter'), ('FM', 'Friends'), ('SWM', 'Star Wars'), ('TMM', 'The Mandalorian'), ('HDM', 'House of the Dragon'), ('GTM', 'Game of Thrones'), ('LKM', 'The Lion King')], max_length=3)),
                ('cartoons_anime_subcategory', models.CharField(blank=True, choices=[('SNC', 'Snoopy'), ('RMC', 'Rick and Morty'), ('LTC', 'Looney Tunes'), ('BBC', 'Bugs Bunny'), ('TC', 'Tweety'), ('SJC', 'Space Jam'), ('TJC', 'Tom and Jerry'), ('SDC', 'Scooby Doo'), ('DC', 'Disney'), ('MMC', 'Mickey Mouse'), ('DDC', 'Donald Duck'), ('SJ', 'Samurai Jack'), ('BC', 'Ben 10'), ('SBC', 'Sponge Bob Square Pants'), ('FDC', 'Fidon Dido'), ('CBC', 'Chotta Beam'), ('MPC', 'Motu Patlu'), ('MC', 'Mowgli'), ('DMC', 'Doremon'), ('JAC', 'Jackiechan Adventure.'), ('LKC', 'Little krishna'), ('SC', 'Shiva'), ('DEC', 'Dora the Explorer')], max_length=3)),
                ('web_series_subcategory', models.CharField(blank=True, choices=[('STW', 'Stranger Things'), ('WW', 'Wednesday'), ('NHW', 'Never Have I Ever'), ('EW', 'Elite'), ('PBW', 'Peaky Blinders'), ('LW', 'Lucifer'), ('ADW', 'All of us Are Dead'), ('SEW', 'Sex Education')], max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='products/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('age', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)])),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', '2X-Large'), ('3XL', '3X-Large'), ('4XL', '4X-Large')], max_length=3)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(choices=[('C', 'Cotton'), ('P', 'Polyester'), ('L', 'Linen'), ('R', 'Rayon'), ('S', 'Spandex')], max_length=1)),
                ('brand', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('discount', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
