# Generated by Django 4.2.7 on 2023-12-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_tshirt_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='marvel_subcategory',
            field=models.CharField(blank=True, choices=[('AVM', 'Avengers'), ('SMM', 'Spider-Man'), ('IMM', 'Iron-Man'), ('CAM', 'Captain America'), ('TM', 'Thor'), ('LM', 'Loki'), ('DSM', 'Doctor Strange'), ('DPM', 'Dead Pool'), ('HM', 'Hulk'), ('BWM', 'Black Widow'), ('VM', 'Venom'), ('WVM', 'Wandavision'), ('AMM', 'Ant-Man'), ('CMM', 'Captain Marvel'), ('SCM', 'Shang Chi'), ('TNM', 'Thanos'), ('BPM', 'Black Panther'), ('EM', 'Eternals')], max_length=3),
        ),
    ]
