# Generated by Django 4.2.7 on 2024-01-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
