# Generated by Django 4.2.7 on 2023-11-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
