# Generated by Django 4.2.7 on 2023-11-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
