# Generated by Django 4.2.7 on 2023-11-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
