# Generated by Django 4.2.7 on 2023-11-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
