# Generated by Django 4.2.7 on 2023-11-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_useraccount_is_verified_alter_useraccount_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
