# Generated by Django 4.2.7 on 2023-11-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
