# Generated by Django 4.2.7 on 2023-11-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_desp', models.TextField()),
                ('product_price', models.CharField(max_length=100)),
                ('name', models.CharField(choices=[('MT', 'Men T-Shirts'), ('WT', 'Women T-Shirts'), ('KT', 'Kids T-Shirts'), ('CH', 'Characters')], default='MT', max_length=2)),
            ],
        ),
    ]
