# Generated by Django 4.2.7 on 2023-11-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_rename_name_category_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='otp_timestamp',
        ),
    ]
