# Generated by Django 4.2.7 on 2023-12-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_delete_category_remove_useraccount_otp_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
