# Generated by Django 4.2.7 on 2023-12-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
